### ISSUE TITLE
does not work! SSL certificate missing

### ISSUE THREAD

**Issue by bc38** [knwin/OpenTopography-DEM-Downloader-qgis-plugin#6]
QGIS Version: 3.28.3-Firenze
Revision: c12bcb2f76c
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.6.2
GEOS version: 3.11.1-CAPI-1.17.1
PROJ version: Rel. 9.1.1, December 1st, 2022
PDAL Version: 2.4.3 (git-version: f8d673)
Start of algorithm execution: 2023-03-10T13:34:07
Running 'OpenTopography DEM Downloader' Algorithm…
Input parameters:

Traceback (most recent call last):
File "C:\Users/admin/AppData/Roaming/QGIS/QGIS3\profiles\BaikalChart/python/plugins\OpenTopography-DEM-Downloader\OpenTopography_DEMDownloader_algorithm.py", line 122, in processAlgorithm
outputs['DownloadFile'] = processing.run('native:filedownloader', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins\processing\tools\general.py", line 116, in run
return Processing.runAlgorithm(algOrName, parameters, onFinish=post_process, feedback=feedback, context=context)
File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins\processing\core\Processing.py", line 187, in runAlgorithm
ret, results = execute(alg, parameters, context, feedback, catch_exceptions=False)
File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins\processing\gui\AlgorithmExecutor.py", line 72, in execute
results, ok = alg.run(parameters, context, feedback, {}, False)
_core.QgsProcessingException: SSL Errors:
Publisher certificate could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users/admin/AppData/Roaming/QGIS/QGIS3\profiles\BaikalChart/python/plugins\OpenTopography-DEM-Downloader\OpenTopography_DEMDownloader_algorithm.py", line 127, in processAlgorithm
raise QgsProcessingException (response.text.split('<error>')[1][:-8])
IndexError: list index out of range

Execution failed after 13.58 seconds

Loading Output Layers
Algorithm "OpenTopography DEM Downloader" completed

**Comment by knwin** [comment]
I think the issue is from the OpenTopography site as it is about SSL certificate. Maybe you can try some time later to check if the site update the ssl certificates or not.
